services:
  - type: web
    name: algocanvas-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: CLIENT_ORIGIN
        value: https://algocans.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: algocanvas-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: algocanvas-db
    databaseName: algocanvas
    user: algocanvas
    plan: free
